package com.codeheadsystems.hofmann;

/**
 * The request sent to the server for elimination.
 *
 * @param hexCodedEcPoint The hex-encoded elliptic curve point generated by the client after blinding the hashed data.
 * @param requestId       A unique identifier for this request, which can be used for tracking and correlation with the server's response.
 */
public record EliminationRequest(String hexCodedEcPoint, String requestId) {
}
